---
- name: Execute initial batch(autonomous) testing setup
  become: true
  when: test_runs|length > 0
  shell:
    cmd: "yes n | {{ exe_path }} batch-setup"
    executable: "{{ shell_exe }}"
  environment:
    PTS_SILENT_MODE: 1
  register: cmd_result

- name: Render Phoronix user configuration
  become: true
  when: user_config is defined and user_config.keys()|length > 0
  template:
    src: "{{ _phoronix_usercfg_file }}.j2"
    dest: "{{ _config_path }}"
    owner: "{{ phoronix_user }}"
    group: "{{ phoronix_user }}"
    mode: 0644
  vars:
    conf: "{{ user_config }}"
  tags:
    - config
