---
# Gather system information according to Phoronix-Test-Suite
- name: Gather Phoronix system information
  when: inspect_system
  command: "{{ exe_path }} system-info"
  register: pts_system_info

- name: Gather Phoronix system diagnostics
  when: inspect_system
  command: "{{ exe_path }} diagnostics"
  register: pts_diagnostics

- name: Gather Phoronix system sensor information
  when: inspect_system
  command: "{{ exe_path }} system-sensors"
  register: pts_sensors

- name: Gather Phoronix system network information
  when: inspect_system
  command: "{{ exe_path }} network-info"
  register: pts_netinfo

# Format PTS collected data
- name: Format PTS system and diagnostic data
  when: inspect_system
  set_fact:
    fmt_pts_info: "{{ pts_system_info.stdout_lines | map('trim') | select | map('regex_replace', ansi_removal_regex) | list }}"
    fmt_pts_diag: "{{ pts_diagnostics.stdout_lines | map('trim') | select | map('regex_replace', ansi_removal_regex) | list }}"
    fmt_pts_sensors: "{{ pts_sensors.stdout_lines | map('trim') | select | map('regex_replace', ansi_removal_regex) | list }}"
    fmt_pts_netinfo: "{{ pts_netinfo.stdout_lines | map('trim') | select | map('regex_replace', ansi_removal_regex) | list }}"
    diagnostic_map: {}

- name: Set PTS diagnostic data map
  when: inspect_system and item|length > 0
  set_fact:
    diagnostic_map: "{{ diagnostic_map | combine({item.split('=')[0]: item.split('=')[1]|default('')}) }}"
  loop: "{{ fmt_pts_diag }}"
