---
- name: Gather recommened Phoronix tests (test-name by subsystem)
  when: run_recommended
  shell:
    cmd: "set -o pipefail && {{ exe_path }} list-recommended-tests | awk '{print $1}'"
    executable: "{{ shell_exe }}"
  register: cmd_result

- name: Format PTS recommended test data
  when: run_recommended
  set_fact:
    fmt_pts_recommended: "{{ cmd_result.stdout_lines | map('trim') | map('regex_replace', ansi_removal_regex) | list }}"
    pts_recommended: []

- name: Sanitize PTS recommended test data
  when: run_recommended
  set_fact:
    pts_recommeneded: "{{ pts_recommended + [item] if 'pts' in item else pts_recommended }}"
  loop: "{{ fmt_pts_recommended }}"

# *** PTS Suite info ***

- name: Gather available Phoronix test suites
  when: run_available
  shell:
    cmd: "set -o pipefail {{ exe_path }} list-available-suites | awk '{print $1}'"
    executable: "{{ shell_exe }}"
  register: cmd_result

- name: Format PTS available test suites
  when: run_available
  set_fact:
    fmt_pts_suites: "{{ cmd_result.stdout_lines | map('trim') | map('regex_replace', ansi_removal_regex) | list }}"
    pts_suites: []

- name: Sanitize PTS available suites data
  when: run_available
  set_fact:
    pts_suites: "{{ pts_suites + [item] if 'pts' in item else pts_suites }}"
  loop: "{{ fmt_pts_suites }}"
