---
- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ phoronix_user }}"
    group: "{{ phoronix_user }}"
  when: install_type == "archive"
  tags:
    - install
    - archive

- name: Download and extract Phoronix archive
  become: true
  unarchive:
    src: "{{ archive_url }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    owner: "{{ phoronix_user }}"
    group: "{{ phoronix_user }}"
    extra_opts:
      - --strip-components
      - '1'
    remote_src: true
  when: install_type == "archive"
  tags:
    - install
    - archive
